### ISSUE TITLE
No RemoveKey or UnsetKeyandValue

### ISSUE THREAD

**Issue by falafflepotatoe** [bitly/go-simplejson#39]
?
please!

**Comment by falafflepotatoe** [comment]
func (j *Json) Unset(key string) {
    	m, err := j.Map()
    	if err != nil {
    		return
	    }
    	delete(m,key)
    }

nvm got it

**Comment by mreiferson** [comment]
There's https://github.com/bitly/go-simplejson/blob/master/simplejson.go#L105-L112

**Comment by falafflepotatoe** [comment]
ah ok ty, i had searched for remove and unset :)
