### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by fireproofsocks** [bitly/go-simplejson#44]
I'm not seeing a single example in the docs.

**Comment by mreiferson** [comment]
Your best bet is gonna be the tests: https://github.com/bitly/go-simplejson/blob/master/simplejson_test.go

**Comment by fireproofsocks** [comment]
It pains me when developers spend so much time developing code and so little time demonstrating it.  Would you at least consider adding a CONTRIBUTING.md file so that others could help fill in the gaps via pull requests?

**Comment by mreiferson** [comment]
There _are_ API [docs](http://godoc.org/github.com/bitly/go-simplejson) that include snippets of code.

I agree that prose documentation would be helpful and we would be happy to merge any PRs contributing them.

**Comment by fireproofsocks** [comment]
Forgive me if I'm missing something, but I do not see a single example on that docs page.
