### ISSUE TITLE
Copyright attribution for go-simplejson

### ISSUE THREAD

**Issue by tpot** [bitly/go-simplejson#47]
Hi.  I noticed that there is no explicit copyright notice, except for the LICENSE file, for files in this repo. Unfortunately the license file does not include Copyright Matt Reiferson.  I am packaging go-simplejson for Debian and I think this might cause some problems with uploading the package.

Is is possible to get a simple change to the license file to add your name somewhere just to make things clear?

Regards,

Tim.

**Comment by mreiferson** [comment]
give it a try and see if you need something more explicit? :grin:
