### ISSUE TITLE
the simple test code is not working corretly

### ISSUE THREAD

**Issue by joyhope** [bitly/go-simplejson#53]
### here is the code ###
package main

import (
	"encoding/json"
	"fmt"
	"os"

	simplejson "github.com/bitly/go-simplejson"
)

type Person struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

func main() {

	//Create the Json string
	var b = []byte(`{"id": 12423434, "Name": "Fernando"}`)

	//Marshal the json to a proper struct
	var f Person
	json.Unmarshal(b, &f)

	//print the person
	fmt.Println(f)

	//unmarshal the struct to json
	result, _ := json.Marshal(f)

	//print the json
	os.Stdout.Write(result)

	fmt.Println("\nSimpleJson")
	json, _ := simplejson.NewJson(b)
	id := json.Get("id").MustInt64(0)
	fmt.Println("id: ", id)
	name, error := json.Get("name").String()
	if error != nil {
		fmt.Println("simple json", error)
	} else {
		fmt.Println(" name: ", name)
	}
}
######

result:
{12423434 Fernando}
{"id":12423434,"name":"Fernando"}
SimpleJson
id:  12423434
simple json type assertion to string failed

**Comment by bruston** [comment]
Change json.Get("name").String() to json.Get("Name").String() and this works fine. The N in Name in your JSON blob is uppercased.
