### ISSUE TITLE
append element to json array

### ISSUE THREAD

**Issue by outprog** [bitly/go-simplejson#54]
i have json like `[{"a":1},{"b":2}]`
want to append {"c":3} to json array
result is `[{"a":1},{"b":2},{"c":3}]`
how? thank you very much

**Comment by jehiah** [comment]
You can use [SetPath](https://godoc.org/github.com/bitly/go-simplejson#Json.SetPath) to update your json object.

```go
package main

import (
	"fmt"
	"github.com/bitly/go-simplejson"
)

func main() {

	j, _ := simplejson.NewJson([]byte(`[{"a":1},{"b":2}]`))
	a := j.MustArray()
	j.SetPath(nil, append(a, map[string]int{"c": 3}))
	body, _ := j.MarshalJSON()
	fmt.Printf("%s", body)

}
```

**Comment by outprog** [comment]
thank you very much.
i added func Append

    // Append object to json array
    func Append(j *Json, val interface{}) *Json {
	    arr, err := j.Array()
	    if err != nil {
		    return nil
	    }
	    res := append(arr, val)
	    return &Json{data: res}
    }

**Comment by zanderwong** [comment]
> thank you very much.
> i added func Append
> 
> ```
> // Append object to json array
> func Append(j *Json, val interface{}) *Json {
>     arr, err := j.Array()
>     if err != nil {
>         return nil
>     }
>     res := append(arr, val)
>     return &Json{data: res}
> }
> ```

it not work for me 

```
func main() {
	j := simplejson.New()
	jsnAry := Append(j, map[string]string{"a": "test"})
	res, err := jsnAry.Encode()
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(string(res))
}

func Append(j *simplejson.Json, val interface{}) *simplejson.Json {
	ary, err := j.Array()
	if err != nil {
		return nil
	}
	res := append(ary, val)
	return &simplejson.Json{res}
}
```

out: `.\main.go:24:26: implicit assignment of unexported field 'data' in simplejson.Json literal`
