### ISSUE TITLE
How to deal with json data with multiple same key

### ISSUE THREAD

**Issue by liboshi** [bitly/go-simplejson#59]
Hi

I have json data like this:
`{ "samekey": "value1",
    "samekey": "value2",
    "samekey": "value3"
}`

How to get the third one? I mean that which built-in function should I use.

Thanks in advance.

**Comment by jehiah** [comment]
You will need to use [encoding/json.Decoder.Token()](https://golang.org/pkg/encoding/json/#Decoder.Token) to accomplish that

https://play.golang.org/p/DuLOeCGSWX
